name: Release
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '__fixtures/**'
      - '__tests__/**'
      - 'TestSolution/**'
      - '.tagpr'
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      pull_request: ${{ steps.tagpr.outputs.pull_request }}
      tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - id: tagpr
        uses: Songmu/tagpr@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  update-tag:
    needs: tagpr
    runs-on: ubuntu-latest
    if: ${{ needs.tagpr.outputs.tag != '' }}
    env:
      MAJOR_TAG: v1
    steps:
      - uses: actions/checkout@v3
      - name: Update Tag
        run: |
          git config --local user.email github-actions[bot]@users.noreply.github.com
          git config --local user.name github-actions[bot]
          git tag -fa ${{ env.MAJOR_TAG }} -m "Release ${{ steps.tagpr.outputs.tag }}"
          git push --force origin ${{ env.MAJOR_TAG }}
