name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run all
  e2e_test:
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest, windows-latest, macos-latest ]
        dotnet-version: [ '3.1', '5.0', '6.0', '7.0' ]
    uses: ./.github/workflows/reusable-e2e.yml
    with:
      operating-system: ${{ matrix.operating-system }}
      dotnet-version: ${{ matrix.dotnet-version }}
  package:
    needs: [lint_test, e2e_test]
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build && npm run package
      - name: Commit compiled code
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.mail '41898282+github-actions[bot]@users.noreply.github.com'
          git diff --exit-code --quiet || (git add . && git commit -m 'Compile' && git push origin ${{ github.head_ref }})
